### ISSUE TITLE
阿尔宙斯无法使用金手指勾选不生效

### ISSUE THREAD

**Issue by hao1196561270** [redball1017/Ryujinx-CN#1]
原版中勾选后可以生效
在汉化版本中勾选修改器后再次打开作弊码界面会显示未勾选

**Comment by redball1017** [comment]
感谢您的反馈！
关于此Bug，我想问一下汉化版勾选后进游戏有生效吗，还是像作弊码界面那样没有生效

**Comment by redball1017** [comment]
我刚刚对比了下汉化版和最新版的Cheat Manager的源代码，除了文字部分之外起来都是一致的。应该不会是我翻译到了非文字类的代码吧。。。

**Comment by hao1196561270** [comment]
> 我刚刚对比了下汉化版和最新版的Cheat Manager的源代码，除了文字部分之外起来都是一致的。应该不会是我翻译到了非文字类的代码吧。。。

经过我测试勾选上进游戏汉化版本是不会生效的
但是我用原版进行勾选作弊码后打开汉化后的龙神进入作弊码界面是勾选的只要我不在汉化版中进行勾选or不勾选直接用汉化版本进游戏是可以正常使用金手指作弊码的

**Comment by hao1196561270** [comment]
> > 我刚刚对比了下汉化版和最新版的Cheat Manager的源代码，除了文字部分之外起来都是一致的。应该不会是我翻译到了非文字类的代码吧。。。
> 
> 经过我测试勾选上进游戏汉化版本是不会生效的 但是我用原版进行勾选作弊码后打开汉化后的龙神进入作弊码界面是勾选的只要我不在汉化版中进行勾选or不勾选直接用汉化版本进游戏是可以正常使用金手指作弊码的

游戏版本1.0.1

**Comment by redball1017** [comment]
> > > 我刚刚对比了下汉化版和最新版的Cheat Manager的源代码，除了文字部分之外起来都是一致的。应该不会是我翻译到了非文字类的代码吧。。。
> > 
> > 
> > 经过我测试勾选上进游戏汉化版本是不会生效的 但是我用原版进行勾选作弊码后打开汉化后的龙神进入作弊码界面是勾选的只要我不在汉化版中进行勾选or不勾选直接用汉化版本进游戏是可以正常使用金手指作弊码的
> 
> 游戏版本1.0.1

勾选后有点保存吗

**Comment by hao1196561270** [comment]
> > > > 我刚刚对比了下汉化版和最新版的Cheat Manager的源代码，除了文字部分之外起来都是一致的。应该不会是我翻译到了非文字类的代码吧。。。
> > > 
> > > 
> > > 经过我测试勾选上进游戏汉化版本是不会生效的 但是我用原版进行勾选作弊码后打开汉化后的龙神进入作弊码界面是勾选的只要我不在汉化版中进行勾选or不勾选直接用汉化版本进游戏是可以正常使用金手指作弊码的
> > 
> > 
> > 游戏版本1.0.1
> 
> 勾选后有点保存吗

有的 没有生效

**Comment by redball1017** [comment]
1.1.8版已修复
